<a href="https://colab.research.google.com/github/aryajayankanichayi/python-learning/blob/main/04_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

array()

In [1]:
from numpy import *
arr=array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


An array can only have values of same datatype.
In the below example numpy automaticaly converts the values to float.
To avoid that we have to specify the datatype.

In [2]:
from numpy import *
arr=array([1,2,3.5,4,5,6])
print(arr.dtype)

float64


In [3]:
from numpy import *
arr=array([1,2,3.5,4,5,6],int)
print(arr.dtype)

int64


linspace()

In [5]:
from numpy import *
arr=linspace(0,15,16)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


arange()

In [6]:
from numpy import *
arr=arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


logspace()

In [7]:
from numpy import *
arr=logspace(0,40,5)
print(arr)

[1.e+00 1.e+10 1.e+20 1.e+30 1.e+40]


zeros()

In [9]:
from numpy import *
arr=zeros(5,int)
print(arr)

[0 0 0 0 0]


ones()

In [10]:
from numpy import *
arr=ones(5,int)
print(arr)

[1 1 1 1 1]


Vectorised Operations

Increment each array values by 5

In [11]:
from numpy import *
arr=array([1,2,3,4,5])
arr=arr+5
print(arr)

[ 6  7  8  9 10]


Add to different arrays

In [12]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=array([3,10,4,5,6])
arr3=arr1+arr2
print(arr3)

[ 4 12  7  9 11]


Array Operations

sum()

In [13]:
from numpy import *
arr1=array([1,2,3,4,5])
print(sum(arr1))

15


min()

In [14]:
from numpy import *
arr1=array([1,2,3,4,5])
print(min(arr1))

1


max()

In [15]:
from numpy import *
arr1=array([1,2,3,4,5])
print(max(arr1))

5


cos()

In [16]:
from numpy import *
arr1=array([1,2,3,4,5])
print(cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


sin()

In [17]:
from numpy import *
arr1=array([1,2,3,4,5])
print(sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


log

In [18]:
from numpy import *
arr1=array([1,2,3,4,5])
print(log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


sqrt()

In [19]:
from numpy import *
arr1=array([1,2,3,4,5])
print(sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


 average()

In [20]:
from numpy import *
arr1=array([1,2,3,4,5])
print(average(arr1))

3.0


unique()

In [22]:
from numpy import *
arr1=array([1,2,4,4,5])
print(unique(arr1))

[1 2 4 5]


sort()

In [23]:
from numpy import *
arr1=array([111,10,3,45,5])
print(sort(arr1))

[  3   5  10  45 111]


concatenate()

In [25]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=array([3,10,4,5,6])
print(concatenate([arr1,arr2]))

[ 1  2  3  4  5  3 10  4  5  6]


Copying An Array

Three ways:

1.  Alising
2. view() -> helps to create new array in differrent location.(shallow copy)
3.  copy() -> deep copy









Alising:
Simply assigning an array to another array.Both arrays will be pointing to the same location

In [26]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=arr1
print(arr2)

[1 2 3 4 5]


view() -> helps to create new array in differrent location.(shallow copy)Both arrays will have different locations.
shallow copy means, when we update one array both array got updated.

In [29]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=arr1.view()
print(arr2)
arr1[1]=10
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 1 10  3  4  5]
[ 1 10  3  4  5]


deep copy

copy() ->  avoids the disadvantage of shallow copy.

In [30]:
from numpy import *
arr1=array([1,2,3,4,5])
arr2=arr1.copy()
print(arr2)
arr1[1]=10
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 1 10  3  4  5]
[1 2 3 4 5]


Write a code to find the maximum element in an without using built-in functions.

In [36]:
from numpy import *
arr1=array([1,25,10,4,50])
max_val=arr1[0] #Assume the first element is maximum.
for i in range(1,len(arr1)):
    if arr1[i]>max_val:
      max_val=arr1[i]
print("Maximum value is:",max_val)

Maximum value is: 50
