<a href="https://colab.research.google.com/github/aryajayankanichayi/python-learning/blob/main/06_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Multidimensional Array

Attributes in multidimensional array

1.   dtype - tells about the type of data
2.   ndim - shows the no.of dimensions
3.   shape - shows the no.of raws and columns
4.   size - shows the size of the entire block





In [ ]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


dtype

In [ ]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
print(arr.dtype)

int64


ndim

In [ ]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


shape

In [ ]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


size

In [ ]:
from numpy import *
arr = array([[1,2,3],[4,5,6]])
print(arr.size)

6


Conversion of multi- dimensional array to one dimensional array

*   flatten()



In [ ]:
from numpy import *
arr1 = array([[1,2,3],[4,5,6]])
arr2 = arr1.flatten()
print(arr2)

[1 2 3 4 5 6]


Coversion of 1-D array to 3-D array

*   reshape()



In [ ]:
from numpy import *
arr1 = array([[1,2,3,4,5,6],[8,9,7,2,4,1]])
arr2= arr1.flatten()
arr3=arr2.reshape(3,4)
print(arr1)
print(" ")
print(arr2)
print(" ")
print(arr3)

[[1 2 3 4 5 6]
 [8 9 7 2 4 1]]
 
[1 2 3 4 5 6 8 9 7 2 4 1]
 
[[1 2 3 4]
 [5 6 8 9]
 [7 2 4 1]]


matrix() function

In [ ]:
from numpy import *
m=matrix('1 2 3;4 5 6;7 8 9')
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


diagional() - print the diagonal elements only

In [ ]:
from numpy import *
m=matrix('1 2 3;4 5 6;7 8 9')
print(diagonal(m))

[1 5 9]


min() - print the minimum element
max() - print the maximum element

In [ ]:
from numpy import *
m=matrix('1 2 3;4 5 6;7 8 9')
print(m.min())

1


In [ ]:
from numpy import *
m=matrix('1 2 3;4 5 6;7 8 9')
print(m.max())

9


Matrix Multiplication

In [2]:
from numpy import *
m1=matrix('1 2 3;6 4 5;1 6 7')
m2=matrix('1 2 3;6 8 5;2 6 7')
m3=m1*m2
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]
